#!/bin/bash
# Version 1.0 by Bryce Powell
# Originally derived from the first version of Lrhorer's script with a similar name

# This script applies patches to any tivoapp from a modified S3 AU/NZ TiVo (ozTiVo)
# running software versions 11.1b through 11.3b8. 

# USE AT YOUR OWN RISK! I will not be held responsible if you break your TiVo.

# It absolutely CANNOT be used with S3 US TiVos. If you run this on a US TiVo, 
# look forward to being able to do nothing with it!

# The UI you've come to love so much will be gone, as well as the ability to boot up.
# More specifically, infinite loops will begin at the "Almost There" screen and all
# you'll have now is a piece of hacked you-know-what.

# Luckily, there's an good solution for this, and it's easier than getting a
# tivoapp off of another TiVo with the same software.

# I've included a way to backup your tivoapp without affecting your drive itself.
# The script will automatically detect the tivoapp and back it up.
# If you want to risk losing access to your TiVo, comment the backup section
# and it will skip that part. I wouldn't recommend it, but if you are feeling
# confident that you know what you're doing, go ahead. Just remember what I said.

# If you want to restore the saved tivoapp, you will have to the the drive out 
# (again) and replace the dysfunctional tivoapp with the backup made earlier. 
# And voila! Congrats on finally getting your TiVo working! Tell yourself not 
# to do that again, and you can continue using your device without the patches.

# If you have any questions or concerns, please message me on Discord
# @snaillover18 or TiVo Community Forum under the username brycepowell.

# Thanks for understanding, and happy patching!

###############################################
###################################################################################################################

# Run from root. Otherwise it will not work.

# Set up the static variables.  Edit as needed.
dstring=`date +%m-%d-%y`

# Check if this is running on a TiVo
# Assumes if the environment variable TIVO_ROOT exists
set | grep -q "TIVO_ROOT="

# Get the software version
sver=`cat /etc/build-version`
sver=${sver##*\ }

if [[ $? -eq 0 ]]
then
        # Set up the static variables for running on a TiVo
        SaveFile=/tvbin/tivoapp.tmp
        Archive=/tvbin/tivoapp.sav
		TarBallDir=/hack/bin
		PatchDir=$TarBallDir/oztivoapp_patches
        HackFile=$PatchDir/"$sver"_patch
        Platform=TiVo
        # Change to the directory containing tivoapp
        cd /tvbin
        # Change the root filesystem to read/write
        mount -o remount,rw /
fi

if ! [[ -f $HackFile ]]
then
        echo "Text file "$sver"_patch not found in /oztivoapp_patches.  Exiting..."
        exit 1
fi

echo Creating temporary tivoapp
cp tivoapp $SaveFile

$HackFile

echo Saving a backup of the old tivoapp
test -e $Archive.$dstring && mv $Archive.$dstring $Archive.$dstring.safety
mv tivoapp $Archive.$dstring
mv $SaveFile tivoapp
[[ $Platform == TiVo ]] && mount -o remount,ro /
echo
echo Done!
